In [15]:
import os
import openpyxl
import pandas as pd

In [16]:
os.listdir('../data')

['2ry_racks_ 2022.xlsx',
 '2ry_racks_ 2023_.xlsx',
 'ADR case-20240312T105907Z-001.zip',
 'causal_sales KPI_BEV.xlsx',
 'causal_sales KPI_JUI.xlsx',
 'causal_sales KPI_SNK.xlsx',
 'causal_sales plan (AOP)_PO1.xlsx',
 '~$causal_sales KPI_BEV.xlsx']

In [20]:
excel = pd.ExcelFile('../data/causal_sales KPI_BEV.xlsx')

In [21]:
excel.sheet_names

['Cube', 'Cube(1)', 'Cube(2)']

In [25]:
excel.parse('Cube').to_csv('../data/causal_sales KPI_BEV.csv', index=False, sep=';')

In [27]:
pd.read_csv('../data/causal_sales KPI_BEV.csv')[10:]

C:\Users\Ansebi\AppData\Local\Temp\ipykernel_7380\4262044391.py:1: DtypeWarning: Columns (1,12,13,14,15,16,17,18,19,20,21,22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('../data/causal_sales KPI_BEV.csv')[10:]

,Unnamed: 0,Cube,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
10,10,10.2022,EAST,FAR EAST,BLAGOVESCHENSK,Alco Group,ALYBION_FULL|L8,Drinks and Beverages,Energy,0.25 L,...,43048.100292,38.544,230.388,219,876,58.4,2869.873353,2.5696,14.6,15.3592
11,11,10.2022,EAST,FAR EAST,BLAGOVESCHENSK,Alco Group,ALYBION_FULL|L8,Drinks and Beverages,Energy,0.449 L,...,31770.008676,85.428,507.6,484.92,1080,60,1765.000482,4.746,26.94,28.2
12,12,10.2022,EAST,FAR EAST,BLAGOVESCHENSK,Alco Group,ALYBION_FULL|L8,Drinks and Beverages,Energy,0.449 L,...,73056.50037,87.801,522.81,498.39,1110,69.375,4566.031273,5.487563,31.149375,32.675625
13,13,10.2022,EAST,FAR EAST,BLAGOVESCHENSK,Alco Group,ALYBION_FULL|L8,Drinks and Beverages,Energy,0.449 L,...,383053.00194,460.362,2764.5,2613.18,5820,291,19152.650097,23.0181,130.659,138.225
14,14,10.2022,EAST,FAR EAST,BLAGOVESCHENSK,Alco Group,ALYBION_FULL|L8,Drinks and Beverages,Energy,0.449 L,...,56799.783621,68.2633,410.788,387.487,863,47.944444,3155.543535,3.792406,21.527056,22.821556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,1048569,3.2023,EAST,URAL,EKATERINBURG,Other Regional OT,YABLOKO_EKT_YA9|L8,Drinks and Beverages,Energy,0.449 L,...,14772.0,32.265,183.192,183.192,408.0,408.0,14772.0,32.265,183.192,183.192
1048570,1048570,3.2023,EAST,URAL,EKATERINBURG,Other Regional OT,YABLOKO_EKT_YA9|L8,Drinks and Beverages,Energy,0.449 L,...,5557.44,6.643,37.716,37.716,84.0,84.0,5557.44,6.643,37.716,37.716
1048571,1048571,3.2023,EAST,URAL,EKATERINBURG,Other Regional OT,YABLOKO_EKT_YA9|L8,Drinks and Beverages,Energy,0.449 L,...,7145.28,8.541,48.492,48.492,108.0,108.0,7145.28,8.541,48.492,48.492
1048572,1048572,3.2023,EAST,URAL,EKATERINBURG,Other Regional OT,YABLOKO_EKT_YA9|L8,Drinks and Beverages,Energy,0.5 L,...,2048.4,5.283,30.0,30.0,60.0,60.0,2048.4,5.283,30.0,30.0
1048573,1048573,3.2023,EAST,URAL,EKATERINBURG,Other Regional OT,YABLOKO_EKT_YA9|L8,Drinks and Beverages,Energy,0.5 L,...,1638.72,4.226,24.0,24.0,48.0,48.0,1638.72,4.226,24.0,24.0